### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by pfumarola** [casbin-js/vue-authz#17]
Error: 
```
This dependency was not found:

* csv-parse/sync in ./node_modules/casbin/lib/esm/persist/helper.js

To install it, you can run: npm install --save csv-parse/sync
```

It seems like the folder structure within the csv-parse node_modules folder was changed. So instead of sync.js being located in csv-parse it is now in csv-parse/lib

**Comment by hsluoyz** [comment]
@pfumarola hi, can you make a PR to fix it?

**Comment by pfumarola** [comment]
Can't reproduce the problem for now 'cause the csv-parse is a dependency of a dependency and I need to have the time to recreate the scenario to investigate better. I've solved locking the dependency for now. I can close the issue and if any other has a similar problem I will do a PR.

**Comment by pfumarola** [comment]
Can't reproduce the problem for now 'cause the csv-parse is a dependency of a dependency and I need to have the time to recreate the scenario to investigate better. I've solved locking the dependency for now. I can close the issue and if any other has a similar problem I will do a PR.
