### ISSUE TITLE
Not loading group policies in auto mode with RBAC model

### ISSUE THREAD

**Issue by pfumarola** [casbin-js/vue-authz#5]
From the localStorage I see that it gets the object from the backend but only the model is loaded. In fact when I do this.$authorizer.can('actionx','resourcey') I get always false.

Perhaps the problem is due to the casbinJsGetPermissionForUser backend function (node-casbin 5.14.0) omitting the _g, user, role_  part in the policies.
I see that casbin.js try to parse the g part but the casbinJsGetPermissionForUser response currently doesn't contain that part.

From [casbin.js](https://github.com/casbin/casbin.js)/[src](https://github.com/casbin/casbin.js/tree/master/src)/Authorizer.ts /
```js
public async initEnforcer(s: string): Promise<void> {
        const obj = JSON.parse(s);
        if (!('m' in obj)) {
            throw Error("No model when init enforcer.");
        }
        const m = casbin.newModelFromString(obj['m']);
        this.enforcer = await casbin.newEnforcer(m);
        if ('p' in obj) {
            for (const sArray of obj['p']) {
                let arr = sArray as string[];
                arr = arr.map(v => v.trim())
                const pType = arr.shift()
                if (pType == 'p'){
                    await this.enforcer.addPolicy(...arr);
                } else if (pType == 'g'){
                    await this.enforcer.addGroupingPolicy(...arr);
                }
            }
        }
    }
```

**Comment by hsluoyz** [comment]
@Zxilly @nodece

**Comment by pfumarola** [comment]
I forced the casbinjs_pfumarola localstorage entry (adding the g part) to the value of:
```js
{

    "m":"[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, obj, act\n[role_definition]\ng = _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub == \"root\"",
    "p":[
        [
            "p",
            "responsabiliProduzione",
            "ricette",
            "view"
        ],
        [
            "g",
            "pfumarola",
            "responsabiliProduzione",
            ""
        ]
    ]

}
```
just to try my theory and it was correct. In fact now e.getPermissionsForUser('pfumarola') returns a not empty array.
However I still get false when I do this.$authorizer.can('view','ricette').

If I set the last part of the localstorage entry to
```js
["g","pfumarola","responsabiliProduzione"] 
```
I get this error: 
```
TypeError: sArray[3] is undefined
    initEnforcer Authorizer.js:154
    step Authorizer.js:52
```
as if expecting a third parameter (Maybe the domain? But my model doesn't have the domain)

**Comment by pfumarola** [comment]
@Zxilly could you please give me an hint to temporarily fix it by my self?

**Comment by hsluoyz** [comment]
@imp2002

**Comment by hsluoyz** [comment]
@imp2002

**Comment by imp2002** [comment]
Try https://github.com/casbin/node-casbin/pull/415
