### ISSUE TITLE
The version of Casbin.js inside vue-authz is older than casbin.js's latest version

### ISSUE THREAD

**Issue by SYJACK7** [casbin-js/vue-authz#6]
From the demo, we need to install both "casbin.js" and "vue-authz".

However, the lastest version of "casbin.js" is ^0.4.1 while the version vue-authz is using is 0.1.3

This will cause a problem that the Authorizer outside is different with the one inside the vue-authz, which means you can't install the plugin successfully

![image](https://user-images.githubusercontent.com/24719750/191684641-0b439826-4395-4bcb-a2cb-477e005b3b03.png)

Can be solved by change both version to 0.1.3.  But it may cause other problem if we are forced to keep using old version.

[Sorry my English is not good enough, I hope the picture can do some help]

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 

/cc @nodece

**Comment by hsluoyz** [comment]
@jakiuncle
